apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
data:
  token: {{ .Values.token | b64enc }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argo-wf-demo-templates
spec:
  entrypoint: ci-pipeline
  serviceAccountName: argo-admin
  arguments:
    parameters:
      - name: image-tag
        value: "ghcr.io/coalery/argo-cd-demo:{{`{{ workflow.uid }}`}}"

  templates:
    - name: ci-pipeline
      dag:
        tasks:
          - name: clone-repo
            template: git-clone
          - name: login-docker
            template: docker-login
            dependencies: [clone-repo]
          - name: build-image
            template: docker-build
            dependencies: [login-docker]
          - name: update-manifest
            template: update-manifest
            dependencies: [build-image]

    - name: git-clone
      container:
        image: alpine/git:latest
        command: [sh, -c]
        args:
          - |
            git clone https://github.com/Coalery/argo-cd-demo.git /workspace
        volumeMounts:
          - name: workdir
            mountPath: /workspace

    - name: docker-login
      container:
        image: docker:20.10.12
        env:
          - name: GH_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
        command: [sh, -c]
        args:
          - |
            echo $GH_TOKEN | docker login ghcr.io -u coalery --password-stdin
            mkdir -p /kaniko/.docker
            cp ~/.docker/config.json /kaniko/.docker/config.json
        volumeMounts:
          - name: workdir
            mountPath: /workspace
          - name: kaniko-secret
            mountPath: /kaniko/.docker

    - name: docker-build
      container:
        image: gcr.io/kaniko-project/executor:v1.23.2
        args:
          - --dockerfile=/workspace/Dockerfile
          - --context=dir:///workspace
          - --destination={{`{{ workflow.parameters.image-tag }}`}}
        volumeMounts:
          - name: workdir
            mountPath: /workspace
          - name: kaniko-secret
            mountPath: /kaniko/.docker

    - name: update-manifest
      container:
        image: bitnami/git:latest
        env:
          - name: GH_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
        command: [sh, -c]
        args:
          - |
            cd /workspace
            IMAGE_TAG={{`{{ workflow.parameters.image-tag }}`}}
            # 이미지 태그를 매니페스트에 업데이트
            sed -i "s|image:.*|image: $IMAGE_TAG|g" manifests/app-deployment.yaml

            git config --global user.email "doralife12@gmail.com"
            git config --global user.name "argo-wf ci"
            git add manifests/app-deployment.yaml
            git commit -m "chore: update image to $IMAGE_TAG"
            git push https://$GH_TOKEN@github.com/Coalery/argo-cd-demo.git
        volumeMounts:
          - name: workdir
            mountPath: /workspace
  
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 0.5Gi
    - metadata:
        name: kaniko-secret
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Mi
