apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Coalery/argo-cd-demo.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
